version: '3.8'

services:
  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootx
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123

  bus-app:
    image: bus:v2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - mysql-standalone

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - bus-app

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password